# Site settings
title: Zalando STUPS
description: > # this means to ignore newlines until "baseurl:"
  The Zalando STUPS platform. Tools and applications to work with AWS.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://zalando-stups.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  zalando-stups
contacts:
  - name: "STUPS team"
    email: tech-stups-pr@zalando.de

sass:
  sass_dir: css

permalink: "/:title"

# Build settings
markdown: kramdown
