# Site settings
title: STUPS Landscape
description: > # this means to ignore newlines until "baseurl:"
  The Zalando STUPS landscape. Tools and applications to work with AWS.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://zalando-stups.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  zalando-stups
contacts:
  - name: "Tobias Sarnowski"
    email: tobias.sarnowski@zalando.de
  - name: "Henning Jacobs"
    email: henning.jacobs@zalando.de

sass:
  sass_dir: css

permalink: "/:title"

# Build settings
markdown: kramdown
